UnitsWebsite/UnitSite/UnitSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Units.urls")),
]

UnitsWebsite/UnitSite/Units/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "Units"
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.HomePage.as_view(), name="home"),
    path("temperature/", views.TemperatureView.as_view(), name="temperature"),
    path("weight/", views.WeightView.as_view(), name="weight"),
    path("length/", views.LenghtView.as_view(), name="length"),
]

UnitsWebsite/UnitSite/Units/models.py
# Create your models here.

UnitsWebsite/UnitSite/Units/forms.py
from django import forms
from django.core.exceptions import ValidationError


class LengthForm(forms.Form):
    CHOICES: dict[str, str] = {
        "mm": "mm",
        "cm": "cm",
        "meter": "meter",
        "km": "km",
        "inches": "inches",
        "foot": "foot",
        "yard": "yard",
        "miles": "miles",
    }
    fromUnit = forms.ChoiceField(
        label="From Unit", widget=forms.Select, choices=CHOICES
    )
    toUnit = forms.ChoiceField(label="To Unit", widget=forms.Select, choices=CHOICES)
    unitValue = forms.FloatField(
        label="Value", min_value=0, max_value=9999999999999, required=True
    )


class WeightForm(forms.Form):
    CHOICES: dict[str, str] = {
        "mg": "mg",
        "g": "g",
        "kg": "kg",
        "ounce": "ounce",
        "pound": "pound",
    }

    fromUnit = forms.ChoiceField(
        label="From Unit", widget=forms.Select, choices=CHOICES
    )
    toUnit = forms.ChoiceField(label="To Unit", widget=forms.Select, choices=CHOICES)
    unitValue = forms.FloatField(
        label="Value", min_value=0, max_value=9999999999999, required=True
    )


class TemperatureForm(forms.Form):
    CHOICES: dict[str, str] = {
        "Celsius": "Celsius",
        "Fahrenheit": "Fahrenheit",
        "Kelvin": "Kelvin",
    }
    MINIMUM_TEMPERATURES = {"Celsius": -273.0, "Fahrenheit": -459.67, "Kelvin": 0.0}
    fromUnit = forms.ChoiceField(
        label="From Unit", widget=forms.Select, choices=CHOICES
    )
    toUnit = forms.ChoiceField(label="To Unit", widget=forms.Select, choices=CHOICES)
    unitValue = forms.FloatField(label="Value", max_value=9999999999999, required=True)

    def clean(self):
        value = self.cleaned_data["unitValue"]
        unit = self.cleaned_data["fromUnit"]
        if value < self.MINIMUM_TEMPERATURES[unit]:
            raise ValidationError(
                f"{unit}'s temperature cannot go bellow {self.MINIMUM_TEMPERATURES[unit]}"
            )

        return self.cleaned_data

UnitsWebsite/UnitSite/Units/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View

from django.forms import ValidationError
from .forms import LengthForm, WeightForm, TemperatureForm
import numpy as np

# Create your views here.


class HomePage(View):

    def get(self, request) -> HttpResponse:
        return render(request, "Units/templates/home.html")


class TemperatureView(View):

    template = "Units/templates/temperature.html"
    FAHRENHEIT_CONSTANT = np.divide(5.0, 9.0)

    def fahrenheitAndCelsius(self, value: float, unit: str) -> float:
        if unit == "Fahrenheit":
            first_mult: float = np.multiply(value, 32.0)
            first_sub: float = np.subtract(first_mult, 32.0)
            return np.multiply(self.FAHRENHEIT_CONSTANT, first_sub)

        first_mult: float = np.multiply(value, np.reciprocal(self.FAHRENHEIT_CONSTANT))
        return np.add(first_mult, 32)

    def fahrenheitAndKelvin(self, value: float, unit: str) -> float:
        if unit == "Fahrenheit":
            first_sub: float = np.subtract(value, 32)
            first_mult: float = np.multiply(
                first_sub, np.reciprocal(self.FAHRENHEIT_CONSTANT)
            )
            return np.add(first_mult, 273.15)

        first_sub: float = np.subtract(value, 273.15)
        first_mult: float = np.multiply(first_sub, self.FAHRENHEIT_CONSTANT)
        return np.add(first_mult, 32)

    def kevinAndCelsius(self, value: float, unit: str) -> float:
        return np.add(value, 273.0) if unit == "Kelvin" else np.subtract(value, 273.0)

    def get(self, request) -> HttpResponse:
        form = TemperatureForm()
        ctx: dict[str, TemperatureForm] = {"form": form}
        return render(request, self.template, context=ctx)

    def post(self, request):
        form = TemperatureForm(request.POST)
        if not form.is_valid():
            ctx = {"form": form, "valid": False}
            return render(request, self.template, ctx)

        data = dict(request.POST.items())
        previousUnit: str = data["fromUnit"]
        newUnit: str = data["toUnit"]
        previousValue = float(data["unitValue"])

        if previousUnit != newUnit:
            match (previousUnit, newUnit):
                case ("Celsius", "Fahrenheit"):
                    newValue: float = self.fahrenheitAndCelsius(
                        previousValue, previousUnit
                    )
                case ("Celsius", "Kelvin"):
                    newValue: float = self.kevinAndCelsius(previousValue, previousUnit)
                case ("Fahrenheit", "Celsius"):
                    newValue: float = self.fahrenheitAndCelsius(
                        previousValue, previousUnit
                    )
                case ("Fahrenheit", "Kelvin"):
                    newValue: float = self.fahrenheitAndKelvin(
                        previousValue, previousUnit
                    )
                case ("Kelvin", "Celsius"):
                    newValue: float = self.kevinAndCelsius(previousValue, previousUnit)
                case ("Kelven", "Fahrenheit"):
                    newValue: float = np.reciprocal(
                        self.fahrenheitAndKelvin(previousValue, previousUnit)
                    )
                case _:
                    raise ValidationError("Unknown unit")
        else:
            newValue = previousValue

        ctx = {
            "previousValue": previousValue,
            "previousUnit": previousUnit,
            "newValue": newValue,
            "newUnit": newUnit,
            "valid": True,
        }

        return render(request, self.template, context=ctx)


class LenghtView(View):

    UNITS: dict[str, float] = {
        "mm": 1000.0,
        "cm": 100.0,
        "inch": 39.3_701,
        "foot": 3.32_084,
        "yard": 1.09_361,
        "meter": 1.0,
        "km": 0.001,
        "miles": 0.000_621_371,
    }

    def get(self, request) -> HttpResponse:
        form = LengthForm()
        ctx: dict[str, LengthForm] = {"form": form}
        return render(request, "Units/templates/length.html", ctx)

    def post(self, request) -> HttpResponse:
        data = dict(request.POST.items())
        previousUnit: str = data["fromUnit"]
        newUnit: str = data["toUnit"]
        previousValue = float(data["unitValue"])
        valueInMeter: float = np.multiply(
            previousValue, np.reciprocal(self.UNITS[previousUnit])
        )
        newValue: float = np.multiply(valueInMeter, self.UNITS[newUnit])
        notationValue: str = np.format_float_scientific(newValue, 5)

        ctx: dict[str, float | str] = {
            "previousValue": previousValue,
            "previousUnit": previousUnit,
            "newValue": notationValue,
            "newUnit": newUnit,
        }

        return render(request, "Units/templates/length.html", context=ctx)


class WeightView(View):

    UNITS: dict[str, float] = {
        "mg": 1000_000.0,
        "g": 1000.0,
        "kg": 1.0,
        "ounce": 35.274,
        "pound": 2.20462,
    }

    def get(self, request) -> HttpResponse:
        form = WeightForm()
        ctx: dict[str, WeightForm] = {"form": form}
        return render(request, "Units/templates/weight.html", context=ctx)

    def post(self, request) -> HttpResponse:
        data = dict(request.POST.items())
        previousUnit: str = data["fromUnit"]
        newUnit: str = data["toUnit"]
        previousValue = float(data["unitValue"])
        valueInMeter: float = np.multiply(
            previousValue, np.reciprocal(self.UNITS[previousUnit])
        )
        newValue: float = np.multiply(valueInMeter, self.UNITS[newUnit])
        notationValue: str = np.format_float_scientific(newValue, 5)

        ctx: dict[str, float | str] = {
            "previousValue": previousValue,
            "previousUnit": previousUnit,
            "newValue": notationValue,
            "newUnit": newUnit,
        }

        return render(request, "Units/templates/weight.html", context=ctx)

UnitsWebsite/UnitSite/Units/templates/Units/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <ul>
        <li><a href="{% url 'Units:temperature' %}">Temperature</a></li>
        <li><a href="{% url 'Units:length' %}">Length</a></li>
        <li><a href="{% url 'Units:weight' %}">Weight</a></li>
    </ul>
</body>
</html>

UnitsWebsite/UnitSite/Units/templates/Units/templates/length.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if request.method == "GET" %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Convert">
    </form>
    
    {% endif %}

    {% if request.method == "POST" %}
    
    <div>
        {{ previousValue }} {{ previousUnit }} equals {{ newValue }} {{ newUnit }}
    </div>
    <div>
        <button type="button" onclick="window.location.href ={% url 'Units:length'%}">Go back</button>
    </div>
    {% endif %}
        
        
</body>
</html>

UnitsWebsite/UnitSite/Units/templates/Units/templates/temperature.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if request.method == "GET" %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Convert">
    </form>
    
    {% endif %}

    {% if request.method == "POST" %}
        {% if valid  == False %}
        <form action="" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Convert">
        </form>
        {% else %}    
        <div>
            {{ previousValue }} {{ previousUnit }} equals {{ newValue }} {{ newUnit }}
        </div>
        <div>
            <button type="button" onclick="window.location.href ={% url 'Units:temperature'%}">Go back</button>
        </div>
        {% endif %}
    {% endif %}
        
        
</body>
</html>

UnitsWebsite/UnitSite/Units/templates/Units/templates/weight.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if request.method == "GET" %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Convert">
    </form>
    
    {% endif %}

    {% if request.method == "POST" %}
    
    <div>
        {{ previousValue }} {{ previousUnit }} equals {{ newValue }} {{ newUnit }}
    </div>
    <div>
        <button type="button" onclick="window.location.href ={% url 'Units:weight'%}">Go back</button>
    </div>
    {% endif %}
        
        
</body>
</html>