PersonalBlog/PersonalBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("blog.urls")),
    path("admin/", admin.site.urls),
]

PersonalBlog/blog/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("", views.ArticleListView.as_view(), name="article-list"),
    path("new", views.ArticleCreateView.as_view(), name="article-create"),
    path("article/<int:pk>", views.ArticleDetailView.as_view(), name="article-detail"),
    path("update/<int:pk>", views.ArticleUpdateView.as_view(), name="article-update"),
    path("delete/<int:pk>", views.ArticleDeleteView.as_view(), name="article-delete"),
    path("admin/", admin.site.urls),
]

PersonalBlog/blog/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Article(models.Model):
    title = models.CharField(verbose_name="Title", max_length=30)
    content = models.TextField(verbose_name="Content", max_length=300)
    publishDate = models.DateTimeField(verbose_name="Published Date", auto_now_add=True)
    updatedDate = models.DateTimeField(verbose_name="Last Updated", auto_now=True)
    author = models.ForeignKey(to=User, on_delete=models.CASCADE)

PersonalBlog/blog/views.py
from django.views.generic import ListView, DetailView
from django.urls import reverse_lazy

from . import owner
from .models import Article

# Create your views here.]


class ArticleListView(ListView):
    model = Article


class ArticleDetailView(DetailView):
    model = Article


class ArticleCreateView(owner.OwnerCreateView):
    model = Article
    fields = ["title", "content"]
    success_url = reverse_lazy("blog:article-list")


class ArticleUpdateView(owner.OwnerUpdateView):
    model = Article
    fields = ["title", "content"]
    success_url = reverse_lazy("blog:article-list")


class ArticleDeleteView(owner.OwnerDeleteView):
    model = Article
    success_url = reverse_lazy("blog:article-list")

PersonalBlog/blog/templates/blog/article_confirm_delete.html
{% extends "./base.html" %} {% block title %}
<title>Delete Confirmation</title>
{% endblock %} {% block content %}
<h1>Are you sure you want to delete {{ article.title }}?</h1>
<form action="" method="post">
  {% csrf_token %}
  <input class="btn btn-danger" type="submit" value="Yes, delete" />
  <button
    class="btn btn-primary"
    type="button"
    onclick="window.location='{% url 'blog:article-list'%}'; return false;"
  >
    Cancel
  </button>
</form>

{% endblock %}

PersonalBlog/blog/templates/blog/article_detail.html
{% extends "./base.html" %} {% block title %}
<title>{{ article.title }}</title> {% endblock %} {% block content %}
<h1>{{ article.title }}</h1>
<h3>{{ article.content }}</h3>
{% endblock %}

PersonalBlog/blog/templates/blog/article_form.html
{% extends "./base.html" %} {% block title %} <title>New Article</title>
{%endblock %} {% block content %}
<p></p>
<table>
  <form action="" method="post">
    {% csrf_token %}
    <div class="row mb-3">
      <label class="col-sm-2 col-form-label" for="title">Title </label>
      <div class="col-sm-10">
        <input class="form-control" type="text" name="title" id="title" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="content" class="col-sm-2 col-form-label">Content</label>
      <div class="col-sm-10">
        <textarea name="content" id="content" class="form-control"></textarea>
      </div>
    </div>
    <input class="btn btn-success" type="submit" value="Submit" />
    <button
      class="btn btn-danger"
      type="button"
      onclick="window.location='{% url 'blog:article-list' %}'; return false;"
    >
      Cancel
    </button>
  </form>
</table>
{% endblock %}

PersonalBlog/blog/templates/blog/article_list.html
{% extends "./base.html" %} {% block title %} <title>Articles</title>
{%endblock %} {% block content %}
<p></p>
<table class="table table-bordered table-light">
  <thead class="table-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Last Updated</th>
      <th scope="col">Published Date</th>
      {% if user.is_staff %}
      <th scope="col">Update</th>
      <th scope="col">Delete</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    <div>
      {% for article in article_list %}
      <tr>
        <th scope="row">{{ article.id }}</th>
        <td>
          <a
            class="page-link"
            href="{% url 'blog:article-detail' pk=article.id %}"
            >{{article.title}}</a
          >
        </td>
        <td>{{article.updatedDate}}</td>
        <td>{{article.publishDate}}</td>
        {% if user.is_staff %}
        <td>
          <a
            class="btn btn-success"
            href="{% url 'blog:article-update' pk=article.id %}"
            class="link-primary"
            >Update</a
          >
        </td>
        <td>
          <a
            class="btn btn-danger"
            href="{% url 'blog:article-delete' pk=article.id %}"
            class="link-primary"
            >Delete</a
          >
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </div>
  </tbody>
</table>

{% if user.is_staff %}
<div>
  <a class="btn btn-primary" href="{% url 'blog:article-create' %}"
    >Make a new post!</a
  >
</div>
{% endif %} {% endblock %}

PersonalBlog/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}{% endblock %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="container">{% block content %} {% endblock content %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>